services:
  - type: worker
    name: internship-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    schedule: "0 * * * *"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SSL_MODE
        sync: false
